# Generated by Django 4.1.6 on 2023-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="stage_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
